from commands.as_witness import AsWitness
from commands.check_consistency import CheckConsistency
from commands.children import Children
from commands.exit import Exit
from commands.experiment import Experiment
from commands.family import Family
from commands.load import Load
from commands.missing import Missing
from commands.person import Person
from commands.witnesses import Witnesses
